#!/usr/bin/env python
# credits: generated by chatGPT
import rospy
from sensor_msgs.msg import PointCloud2

def callback(data):
    # Update the timestamp to the current time
    data.header.stamp = rospy.Time.now()

    # Publish the modified PointCloud2 message
    pub.publish(data)

if __name__ == '__main__':
    # Initialize the node
    rospy.init_node('point_cloud_time_updater', anonymous=True)

    # Subscribe to the original PointCloud2 topic
    rospy.Subscriber('/camera/depth/color/points_recorded', PointCloud2, callback)

    # Create a publisher for the updated PointCloud2 topic
    pub = rospy.Publisher('/camera/depth/color/points', PointCloud2, queue_size=10)

    # Spin until the node is terminated
    rospy.spin()

