- name: "Table_segment"
  require_surface: false
  parent_frame_id: "base_link"
  child_frame_id: "camera_link"
  bounding_frame_id: "base_link"
  segmentation_frame_id: "base_link"
  z_min: 0.7
  z_max: 0.8
  y_min: -0.5
  y_max: 0.5
  x_min: 0.5
  x_max: 3